#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.

set -e

autoreconf -i --force
rm -rf autom4te.cache

# Generate manual pages.
version=`grep '^lbcd' NEWS | head -1 | cut -d' ' -f2`
pod2man --release="$version" --center=lbcd --section=8 lbcd.pod > lbcd.8.in
pod2man --release="$version" --center=lbcd lbcdclient > lbcdclient.1
