#! /bin/sh
### BEGIN INIT INFO
# Provides:             lbcd
# Required-Start:       $remote_fs $network $syslog
# Required-Stop:        $remote_fs $network $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    Load balancer client daemon
# Description:          Provides system load, login, and service information
#                       via UDP, intended primarily for use with the lbnamed
#                       load balancing system.
### END INIT INFO
#
# Written by Russ Allbery <rra@stanford.edu>
# Based on the dh-make template written by:
#
#     Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#     Modified for Debian 
#     by Ian Murdock <imurdock@gnu.ai.mit.edu>.

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/lbcd
NAME=lbcd
DESC=lbcd
PIDDIR=/var/run/lbcd
OWNER=lbcd
GROUP=lbcd

test -x $DAEMON || exit 0

# Include lbcd defaults if available.
if [ -f /etc/default/lbcd ] ; then
    . /etc/default/lbcd
fi

# Create a dir for the pidfile since lbcd runs nonroot
create_piddir()
{
    mkdir -p $PIDDIR
    chown $OWNER:$GROUP $PIDDIR
}

case "$1" in
start)
    # Don't start lbcd if NO_START is set.
    if [ "$NO_START" = 1 ] ; then
        echo "Not starting $DESC (see /etc/default/$NAME)"
        exit 0
    fi
    echo -n "Starting $DESC: "
    create_piddir
    start-stop-daemon -c lbcd -g lbcd --start --quiet \
        --pidfile $PIDDIR/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
    echo "$NAME."
    ;;
stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon --stop --quiet --pidfile $PIDDIR/$NAME.pid \
        --oknodo --exec $DAEMON
    echo "$NAME."
    ;;
reload)
    ;;
restart|force-reload)
    echo -n "Restarting $DESC: "
    create_piddir
    start-stop-daemon --stop --quiet --pidfile $PIDDIR/$NAME.pid \
        --oknodo --exec $DAEMON
    sleep 1
    start-stop-daemon -c lbcd -g lbcd --start --quiet \
        --pidfile $PIDDIR/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
    echo "$NAME."
    ;;
*)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
